version: '2.1'
services:
  app:
    build: ./flask
    ports:
      - '5000:5000'
    volumes:
      - ./flask/app:/app
  db:
    image: postgres:10.3-alpine
    restart: always
    environment:
        POSTGRES_USER: app
        POSTGRES_PASSWORD: password
    ports:
      - '54321:5432'
